version: '3.8'

services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    volumes:
      - localstack_data:/tmp/localstack/data

volumes:
  localstack_data: